/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.Vista;

import bookstore.BaseDatos.Conexion;
import bookstore.Controlador.RegistroVentaControlador;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jeric
 */
public class VistaRegistroVenta extends javax.swing.JFrame {

   
    
    public VistaRegistroVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtFechaActual.setText(fecha());
        
        
        desahabilitarCamposPrincipales();        

        //Deshabilitando campos cliente
        deshabilitarCamposCliente();
        
        //Deshabilitando campos Calcular
        deshabilitarCamposCalcular();
        
        //Llenando datos a la lista despegable
        Conexion c = new Conexion();
        c.getConnection();
        try {
            ResultSet resultado = c.consultarRegistros("SELECT IDPUBLICACION FROM PUBLICACION GROUP BY IDPUBLICACION");
            while(resultado.next()){
                jComboVenta.addItem(resultado.getString("IDPUBLICACION"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        try {
            ResultSet resultado = c.consultarRegistros("SELECT IDEMPLEADO FROM USUARIO GROUP BY IDEMPLEADO");
            while(resultado.next()){
                jComboEmpleado.addItem(resultado.getString("IDEMPLEADO"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        c.desconexion();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombrePublicacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAutorPublicacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtIGV = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jComboVenta = new javax.swing.JComboBox<>();
        jComboEmpleado = new javax.swing.JComboBox<>();
        jCalcular = new javax.swing.JButton();
        txtFechaActual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO VENTA");

        jLabel2.setText("ID PUBLICACION");

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("NOMBRE DE LA PUBLICACION");

        jLabel4.setText("AUTOR DE LA PUBLICACION");

        jLabel5.setText("STOCK (UU)");

        jLabel6.setText("PRECIO UNITARIO S/.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txtNombrePublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecioUnitario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txtAutorPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(txtStock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutorPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel7.setText("INFORMACION DE LA PUBLICACION");

        jLabel8.setText("INFORMACION CLIENTE");

        jLabel9.setText("NOMBRE DEL CLIENTE");

        jLabel10.setText("ID DEL EMPLEADO");

        jLabel11.setText("CANTIDAD (UU)");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel12.setText("DESCUENTO %");

        jLabel13.setText("SUBTOTAL S/.");

        txtSubtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSubtotalKeyTyped(evt);
            }
        });

        jLabel14.setText("TOTAL A PAGAR S/.");

        jLabel15.setText("IGV %");

        txtIGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIGVActionPerformed(evt);
            }
        });
        txtIGV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIGVKeyTyped(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR VENTA");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("FECHA");

        jCalcular.setText("CALCULAR");
        jCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtSubtotal)
                                                    .addComponent(txtCantidad)
                                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(30, 30, 30)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15)
                                            .addComponent(txtIGV, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(jCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtDescuento)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(96, 96, 96))
                                    .addComponent(txtFechaActual)))
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jComboVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jBuscar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBuscar)
                            .addComponent(jComboVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(8, 8, 8)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalcular))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel16))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIGVActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        VistalPrincipal principal = new VistalPrincipal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // TODO add your handling code here:
        Conexion c = new Conexion();
        c.getConnection();
        try {
            String datoSeleccion = (String)jComboVenta.getSelectedItem();
            String sentenciaSQL = String.format("SELECT TITULO, AUTOR, PRECIO, STOCK FROM PUBLICACION WHERE IDPUBLICACION = '%s'", datoSeleccion);
            ResultSet resultado = c.consultarRegistros(sentenciaSQL);
            while(resultado.next()){
                System.out.println(resultado.getString("TITULO"));
                System.out.println(resultado.getString("AUTOR"));
                System.out.println(resultado.getString("PRECIO"));
                System.out.println(resultado.getString("STOCK"));
                
                agregarDatosCampos(resultado.getString("TITULO"), resultado.getString("AUTOR"), resultado.getString("PRECIO"), resultado.getString("STOCK"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        c.desconexion();
        habilitarCamposCliente();
    
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalcularActionPerformed
        // TODO add your handling code here:
        RegistroVentaControlador calcular = new RegistroVentaControlador();
        
        int precioUnitario = Integer.parseInt(txtPrecioUnitario.getText());
        int cantidad = Integer.parseInt(txtCantidad.getText());
        double descuento = calcular.calculoDescuento(cantidad);
        double igv = obtenerIGV();
        double subtotal = calcular.subtotal(cantidad, precioUnitario, descuento);
        double totalPago = Math.round(calcular.totalPago(subtotal, igv)*100)/100;
        
        System.out.println(precioUnitario);
        System.out.println(cantidad);
        System.out.println(descuento);
        System.out.println(igv);
        System.out.println(subtotal);
        System.out.println(totalPago);
        
        String descuentoFinal = String.valueOf(descuento * 100) + '%';
        String igvFinal = String.valueOf(igv * 100) + '%';
        
        txtSubtotal.setText(String.valueOf(subtotal));
        txtIGV.setText(String.valueOf(igvFinal));
        txtDescuento.setText(String.valueOf(descuentoFinal));
        txtTotal.setText(String.valueOf(totalPago));
        
        btnRegistrar.setEnabled(true);
    }//GEN-LAST:event_jCalcularActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Ingresar solo Numeros");
        }
    }//GEN-LAST:event_txtCantidadKeyTyped
    
    private void txtSubtotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubtotalKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSubtotalKeyTyped

    private void txtIGVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIGVKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIGVKeyTyped

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        int ventaContador = obtenerVenta();
        ventaContador += 1;
        
        String ventaContadorS = String.valueOf(ventaContador);
        
        System.out.println(ventaContador);
        
        RegistroVentaControlador datos = recuperarDatosVenta();
        
        String fecha = txtFechaActual.getText();        
        int idEmpleado = Integer.parseInt((String)jComboEmpleado.getSelectedItem());
        String numeroPublicacion = (String)jComboVenta.getSelectedItem();
        int stock = Integer.parseInt(txtStock.getText());
        int stockActual = stock - datos.getCantidad(); 
              
        int descuento = (int)Math.round(datos.getDescuento());
        int subtotal = (int)Math.round(datos.getSubtotal());
        int igv = (int)Math.round(datos.getIgv());
        int total = (int)Math.round(datos.getTotal());
        
        String sentenciaInsertarSQL = String.format("INSERT INTO VENTA VALUES (%d, '%s', '%s', %d, '%s', %d, %d, %d, %d, %d, %d)", ventaContador, datos.getNombreCliente(), fecha, idEmpleado, numeroPublicacion, datos.getCantidad(), datos.getPrecio(), descuento, subtotal, igv, total);
        String sentenciaUpdateSQL = String.format("UPDATE CONTROL SET VALOR = '%s' WHERE PARAMETRO = 'VENTA'", ventaContadorS);
        String actualizarStockSQL = String.format("UPDATE PUBLICACION SET STOCK = %d WHERE IDPUBLICACION = '%s'", stockActual, numeroPublicacion);
        
        if(stock > datos.getCantidad()){
            Conexion c = new Conexion();
            c.getConnection();


            c.ejecutarSentenciaSQL(sentenciaInsertarSQL);
            c.ejecutarSentenciaSQL(sentenciaUpdateSQL);
            c.ejecutarSentenciaSQL(actualizarStockSQL);

            c.desconexion();

            JOptionPane.showMessageDialog(null, "Venta Realizada con exito");

            desahabilitarCamposPrincipales();        

            //Deshabilitando campos cliente
            deshabilitarCamposCliente();

            //Deshabilitando campos Calcular
            deshabilitarCamposCalcular();

            limpiarCampos();
        
        }else{
            JOptionPane.showMessageDialog(null, "No hay Stock suficiente para la cantidad solicitada");
        }
        

        
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    public void agregarDatosCampos(String titulo, String autor, String precioUnitario, String stock){
        txtNombrePublicacion.setText(titulo);
        txtAutorPublicacion.setText(autor);
        txtPrecioUnitario.setText(precioUnitario);
        txtStock.setText(stock);
    }
    
    public RegistroVentaControlador recuperarDatosVenta(){
        RegistroVentaControlador datos = new RegistroVentaControlador();
        
        int cantidad = Integer.parseInt(txtCantidad.getText());
        int precio = Integer.parseInt(txtPrecioUnitario.getText());
        double descuento = datos.calculoDescuento(cantidad);
        double igv = obtenerIGV();
        double subtotal = datos.subtotal(cantidad, precio, igv);
        double totalPago = datos.totalPago(subtotal, descuento);
        
        datos.setNombreCliente(txtNombreCliente.getText());
        datos.setCantidad(cantidad);
        datos.setPrecio(precio);
        datos.setDescuento(descuento);
        datos.setIgv(igv);
        datos.setSubtotal(subtotal);
        datos.setTotal(totalPago);
        
        return datos;        
    }
    
    public static String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);
    }
    
        
    public double obtenerIGV(){
        Conexion c = new Conexion();
        c.getConnection();
        String sentenciaSQL = "SELECT VALOR FROM CONTROL WHERE PARAMETRO = 'IGV'";
        ResultSet resultado = c.consultarRegistros(sentenciaSQL);
        double igv = 0;
        try {
            while(resultado.next()){
                 igv = Double.parseDouble(resultado.getString("VALOR"));
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        return igv;
    }
    
    public int obtenerVenta(){
        Conexion c = new Conexion();
        c.getConnection();
        String sentenciaSQL = "SELECT VALOR FROM CONTROL WHERE PARAMETRO = 'VENTA'";
        ResultSet resultado = c.consultarRegistros(sentenciaSQL);
        int ventaContador = 0;
        try {
            while(resultado.next()){
                 ventaContador = Integer.parseInt(resultado.getString("VALOR"));
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        return ventaContador;
    }
    
    public void deshabilitarCamposCliente(){
        txtNombreCliente.setEditable(false);
        txtCantidad.setEditable(false);
    }
    
    public void habilitarCamposCliente(){
        txtNombreCliente.setEditable(true);
        txtCantidad.setEditable(true);
    }
    
    public void deshabilitarCamposCalcular(){
        txtSubtotal.setEditable(false);
        txtIGV.setEditable(false);
        txtDescuento.setEditable(false);
        txtTotal.setEditable(false);
    }
    
    private void desahabilitarCamposPrincipales() {
         //Deshabilitando Campos
        txtFechaActual.setEditable(false);
        txtNombrePublicacion.setEditable(false);
        txtAutorPublicacion.setEditable(false);
        txtPrecioUnitario.setEditable(false);
        txtStock.setEditable(false);
        btnRegistrar.setEnabled(false);        
    }
    
    private void limpiarCampos(){
        txtNombrePublicacion.setText(null);
        txtAutorPublicacion.setText(null);
        txtPrecioUnitario.setText(null);
        txtStock.setText(null);
        txtNombreCliente.setText(null);
        txtCantidad.setText(null);
        txtSubtotal.setText(null);
        txtIGV.setText(null);
        txtDescuento.setText(null);
        txtTotal.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jCalcular;
    private javax.swing.JComboBox<String> jComboEmpleado;
    private javax.swing.JComboBox<String> jComboVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAutorPublicacion;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFechaActual;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombrePublicacion;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables


}
