/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.Vista;

import bookstore.BaseDatos.Conexion;
import bookstore.Controlador.RegistroControlador;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author jeric
 */
public class VistaRegistroPublicacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroPublicacion
     */
    String datoSeleccion = "";
    
    public VistaRegistroPublicacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //campos deshabilitados Permanentemente
        txtPublicacion.setEditable(false);
        
        desabilitarCampos();
        
        
        //Llenando datos a la lista despegable
        Conexion c = new Conexion();
        c.getConnection();
        try {
            ResultSet resultado = c.consultarRegistros("SELECT IDTIPO FROM PUBLICACION GROUP BY IDTIPO");
            while(resultado.next()){
                jComboPublic.addItem(resultado.getString("IDTIPO"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        c.desconexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboPublic = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPublicacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEdicion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE NUEVA PUBLICACION");

        jLabel2.setText("TIPO");

        jLabel3.setText("ID PUBLICACION");

        jLabel4.setText("TITULO");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        jLabel5.setText("AUTOR");

        jLabel6.setText("Nº DE EDICION");

        txtEdicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdicionKeyTyped(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel7.setText("CANTIDAD o STOCK");

        jLabel8.setText("PRECIO UNITARIO");

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addComponent(txtAutor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(19, 19, 19)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNuevo))
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboPublic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VistalPrincipal principal = new VistalPrincipal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        txtPublicacion.setText(null);
        
        habilitarCampos();
        
        //Guardando los datos del Usuario
        datoSeleccion = (String)jComboPublic.getSelectedItem();
         
        String sentenciaSQL = "";
            switch(datoSeleccion){
                case "LIB":
                    sentenciaSQL = "SELECT CONTADOR FROM TIPO WHERE IDTIPO LIKE 'LIB'";
                    break;
                case "REV":
                    sentenciaSQL = "SELECT CONTADOR FROM TIPO WHERE IDTIPO LIKE 'REV'";
                    break;
                case "SEP":
                    sentenciaSQL = "SELECT CONTADOR FROM TIPO WHERE IDTIPO LIKE 'SEP'";
                    break;
                default:
                    System.out.println("Error");
                    break;
            }
        
        Conexion c = new Conexion();
        c.getConnection();
        try {
            ResultSet resultado = c.consultarRegistros(sentenciaSQL);
            while(resultado.next()){
                System.out.println(resultado.getString("CONTADOR"));
                int numero = Integer.parseInt(resultado.getString("CONTADOR"));
                numero += 1;
                
                String idPublicidad = "";
                if (numero >= 10) {
                    idPublicidad = datoSeleccion + "000" + numero;                    
                }else if (numero >= 100){
                    idPublicidad = datoSeleccion + "00" + numero;  
                }else {
                    idPublicidad = datoSeleccion + "0000" + numero;
                }
                
                agregarIdPublicacion(idPublicidad);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        c.desconexion();
       
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:

        
        
        String idPublicacion = txtPublicacion.getText();
        String tipoPublicacion = (String)jComboPublic.getSelectedItem();
        int numero = numeroContador();

        RegistroControlador datosVista = recuperarDatosVista();
        
        Conexion c = new Conexion();
        c.getConnection();
        
        String sentenciaInsertarSQL = String.format("INSERT INTO PUBLICACION VALUES ('%s','%s','%s','%s',%d,%d,%d)", idPublicacion, datosVista.getTitulo(), tipoPublicacion, datosVista.getAutor(), datosVista.getNumeroEdicion(), datosVista.getCantidadStock(), datosVista.getPrecio() );
        
        String sentenciaUpdateSQL = String.format("UPDATE TIPO SET CONTADOR = %d WHERE IDTIPO = '%s'", numero, tipoPublicacion);
        
        c.ejecutarSentenciaSQL(sentenciaInsertarSQL);
        c.ejecutarSentenciaSQL(sentenciaUpdateSQL);
            
        c.desconexion();
        
        JOptionPane.showMessageDialog(null, "Registro realizado con exito");
        
        limpiarCampos();
        desabilitarCampos();
        
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtEdicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdicionKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Ingresar solo Numeros");
        }
    }//GEN-LAST:event_txtEdicionKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Ingresar solo Numeros");
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Ingresar solo Numeros");
        }
    }//GEN-LAST:event_txtPrecioKeyTyped
    
    public RegistroControlador recuperarDatosVista(){
        
        RegistroControlador datos = new RegistroControlador();
        
        int numeroEdicion = Integer.parseInt(txtEdicion.getText());
        int cantidadStock = Integer.parseInt(txtCantidad.getText());
        int precio = Integer.parseInt(txtPrecio.getText());
        
        datos.setTitulo(txtTitulo.getText());
        datos.setAutor(txtAutor.getText());
        datos.setNumeroEdicion(numeroEdicion);
        datos.setCantidadStock(cantidadStock);
        datos.setPrecio(precio);
        
        return datos;        
    }
    
    public void agregarIdPublicacion(String idPublicacion){ 
                            
        txtPublicacion.setText(idPublicacion);
    }
    
    public int numeroContador(){
        //Para saber el contador
        datoSeleccion = (String)jComboPublic.getSelectedItem();
        
        String sentenciaSQL = "";
            switch(datoSeleccion){
                case "LIB":
                    sentenciaSQL = "SELECT CONTADOR FROM TIPO WHERE IDTIPO LIKE 'LIB'";
                    break;
                case "REV":
                    sentenciaSQL = "SELECT CONTADOR FROM TIPO WHERE IDTIPO LIKE 'REV'";
                    break;
                case "SEP":
                    sentenciaSQL = "SELECT CONTADOR FROM TIPO WHERE IDTIPO LIKE 'SEP'";
                    break;
                default:
                    System.out.println("Error");
                    break;
            }
        
        Conexion c = new Conexion();
        c.getConnection();
        
        ResultSet resultado = c.consultarRegistros(sentenciaSQL);
        int numero = 0;
        try {
            while(resultado.next()){
                 numero = Integer.parseInt(resultado.getString("CONTADOR"));
                 numero += 1;
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        return numero;
    }
    
    private void desabilitarCampos() {
        //Campos deshabilitados Parcialmente
        txtTitulo.setEditable(false);
        txtAutor.setEditable(false);
        txtEdicion.setEditable(false);
        txtCantidad.setEditable(false);
        txtPrecio.setEditable(false);
        btnRegistrar.setEnabled(false);
        
    }
    
    private void habilitarCampos() {
        //Habilitados campos
        txtTitulo.setEditable(true);
        txtAutor.setEditable(true);
        txtEdicion.setEditable(true);
        txtCantidad.setEditable(true);
        txtPrecio.setEditable(true);
        btnRegistrar.setEnabled(true);
    }   
    
    private void limpiarCampos(){
        txtPublicacion.setText(null);
        txtTitulo.setText(null);
        txtAutor.setText(null);
        txtEdicion.setText(null);
        txtCantidad.setText(null);
        txtPrecio.setText(null);
        btnRegistrar.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPublicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroPublicacion().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboPublic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPublicacion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
